#  ansible-playbook packages.yml 

- name: Introduction to packages
  hosts: local
#  connection: local
  become: true

  tasks:
  - name: create htop
    ansible.builtin.package:
      name: htop
      state: present
  - name: create pip
    ansible.builtin.package:
      name: python3-pip
      state: present
#  - name: install nginix
#    ansible.builtin.include_role:
#      name: nginxinc.nginx
  
#  roles:
#    - name: geerlingguy.nginx
#      version: 3.1.4